base_url: "https://api.genius.com"
lyrics_path:
  raw_inputs: "./data/lyrics/raw_lyrics"
  cleaned_inputs: "./data/lyrics/cleaned_lyrics"
  embeddings: "./data/embeddings"
artists:
  - Nf

kNN: 5
prompt: I'm feeling kinda down lately, but somewhat optimistic. I can see better times coming.